<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="yahia" failures="1" tests="1" name="Login test" time="7.368" errors="0" timestamp="2023-05-05T19:14:24 EDT">
  <testcase classname="us.piit.automationpractice.LoginTest" name="validCredential" time="1.507">
    <failure type="java.lang.AssertionError" message="expected [] but found [your logo]">
      <![CDATA[java.lang.AssertionError: expected [] but found [your logo]
at us.piit.automationpractice.LoginTest.validCredential(LoginTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validCredential -->
</testsuite> <!-- Login test -->
